In [1]:
import numpy as np
import scipy
import scipy.ndimage as nd
from PIL import Image

In [2]:
# read in 3 images as numpy arrays
img1 = Image.open('img01.jpg')
img1 = np.asarray(img1, dtype=np.int64)
img1 = np.transpose(img1, (1,0,2))

img2 = Image.open('img02.jpg')
img2 = np.asarray(img2, dtype=np.int64)
img2 = np.transpose(img2, (1,0,2))

img3 = Image.open('img03.jpg')
img3 = np.asarray(img3, dtype=np.int64)
img3 = np.transpose(img3, (1,0,2))

In [3]:
eps = 0.01

In [4]:
def gen_temp_arrays(arr, num):
    arr1 = np.zeros((len(arr), len(arr[0]), num))
    return arr1

In [26]:
def find_wij(pixel, means, probs, j):
#     pixel -= 255
    val = -0.5*(((pixel) - means[j]).T @ ((pixel) -means[j]))
    print(val + 9537.5)
    return
    numer = np.exp(val)*probs[j]
    denom = 0
    print(numer)
    for i in range(j):
        denom += np.exp(-0.5*(((pixel) -means[i]).T @ ((pixel) - means[i])))*probs[i]
    
    print(denom)
    return numer / denom

In [27]:
# After reading
def em_step(num_means, image):
    init_pi = np.full((num_means,), 1./num_means)
#     print(init_pi)
    init_mean = np.zeros((num_means, 3))
    for m in range(num_means):
        rand_row = np.random.randint(0, len(image))
        rand_col = np.random.randint(0, len(image[0]))
#        print(image[rand_row][rand_col])
        init_mean[m] = image[rand_row][rand_col]
        
#     print(init_mean)
    temp_probs = gen_temp_arrays(image, num_means)
    for mean in range(len(init_mean)):
        for i in range(len(image)):
            for j in range(len(image[0])):
                temp_pixel = image[i][j]
                print(image[i][j])
                wij = find_wij(temp_pixel, init_mean, init_pi, mean)
                print(wij)
                temp_probs[i][j][mean] = wij
em_step(10, img1)

[151 191 105]
-15735.0
None
[152 190 105]
-15725.0
None
[155 191 104]
-16251.5
None
[156 191 101]
-16192.5
None
[160 191  98]
-16601.0
None
[163 190  95]
-16721.5
None
[164 190  91]
-16639.0
None
[165 190  89]
-16683.5
None
[167 189  88]
-16793.5
None
[167 188  87]
-16585.5
None
[166 186  87]
-16121.0
None
[164 184  85]
-15397.0
None
[161 183  85]
-14779.0
None
[158 179  84]
-13683.0
None
[155 176  83]
-12753.5
None
[151 175  81]
-11927.0
None
[147 169  86]
-10785.5
None
[146 170  86]
-10779.5
None
[143 168  87]
-10149.5
None
[138 166  89]
-9323.0
None
[133 165  90]
-8601.5
None
[131 164  93]
-8395.5
None
[126 163  94]
-7715.0
None
[122 161  94]
-6989.0
None
[118 159  93]
-6222.5
None
[114 156  92]
-5355.5
None
[108 152  89]
-4077.0
None
[102 150  88]
-3195.5
None
[ 99 149  90]
-2909.5
None
[ 96 147  90]
-2409.0
None
[ 93 146  90]
-2032.0
None
[ 91 146  89]
-1803.5
None
[ 95 146  90]
-2208.0
None
[ 94 145  89]
-1952.5
None
[ 93 143  90]
-1703.5
None
[ 92 140  88]
-1185.5
None
[ 89 137 

KeyboardInterrupt: 

In [ ]:
# img1
info1, info2, info3 = gen_temp_arrays(img1)
